site_name: eWiz
site_url: !ENV READTHEDOCS_CANONICAL_URL

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            merge_init_into_class: true
            inherited_members: true

extra_javascript:
  - javascript/readthedocs.js

nav:
  - Home: index.md
  - API Reference:
    - Overview: api-reference/index.md
    - Data Readers: api-reference/data-readers.md
    - Renderers: api-reference/renderers.md
